const data = {
    products:[
        {
            _id:'1',
            name:'car1',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'cars',
            rating:1.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'car2',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:120,
            countInStock:3,
            brand:'cars',
            rating:5,
            numReviews:15,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'car3',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:120,
            countInStock:5,
            brand:'cars',
            rating:2.5,
            numReviews:8,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'car4',
            category:'Shirts',
            image:'/images/p4.jpg',
            price:120,
            countInStock:2,
            brand:'cars',
            rating:3.5,
            numReviews:3,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'car5',
            category:'Shirts',
            image:'/images/p5.jpg',
            price:120,
            countInStock:0,
            brand:'cars',
            rating:4.0,
            numReviews:1,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'car6',
            category:'Shirts',
            image:'/images/p5.jpg',
            price:1250,
            countInStock:2,
            brand:'cars',
            rating:1.0,
            numReviews:1,
            description:'high quality product',
        },
    ]
};

export default data;